import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div className="bg-black min-h-screen">
      <Head>
        <title>Slian - Coming soon ...</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <section className="flex flex-col items-center justify-center h-screen pr-12">
        <div className="flex flex-col items-center justify-center">
          <Image src="/slian-logo.png" alt="Slian Logo" width={170} height={54} />
          <h2 className="text-lg text-white font-thin mt-4 tracking-widest animate-pulse">Coming soon</h2>
        </div>
      </section>

      <footer className="flex flex-row justify-center text-white absolute bottom-5 w-full text-xs" >
        <a
          href="https://www.actualize.de"
          target="_blank"
          rel="noopener noreferrer"
          className="flex flex-row justify-center items-center"
        >
          <span className="text-right pr-2 pb-0">
            Powered by
          </span>

          <span className="">
            <Image src="/actualizelogo.svg" alt="Actualize Logo" width={110} height={24} />
          </span>
        </a>
      </footer>
    </div>
  )
}
